# Site settings
title: 周睿的中文博客 | Rui Zhou
description: 个人随笔与课程笔记存档
url: "https://zirconeey.github.io"
baseurl: ""

author:
  name: 周睿 (Rui Zhou)
  email: ruizhou@psu.edu

# Build settings
markdown: kramdown
permalink: /posts/:year-:month-:day-:title/

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .gitignore
