# Site settings
title: 周睿的中文博客 | Rui Zhou
description: 个人随笔与课程笔记存档
url: "https://zirconeey.github.io"
baseurl: ""

author:
  name: 周睿 (Rui Zhou)
  email: ruizhou@psu.edu

# Build settings
markdown: kramdown
permalink: /posts/:year-:month-:day-:title/

# Plugins (GitHub Pages supported)
plugins:
  # - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .gitignore

# Collections (if needed)
collections:
  notes:
    output: true            # 让每一篇笔记生成独立的网页
    permalink: /notes/:path/ # URL 路径保持与文件夹结构一致

study_order:
  - adv-micro-psu
  - adv-metrics-pku
  - adv-micro-pku
  - interm-metrics
  - interm-macro
  - public-econ
  - monetary-econ
  - game-theory
  - causal-id
  - causal-inference
  - china-econ
  - adv-macro-psu
  - real-anal
  - psy-stat-I
  - psy-stat-II
  - or
  - china-hist
  - corp-fin
  - accounting
  - marxism
  - mao-thought
  - tennis
